SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict DbcH9Am7DhcOiy5HJbWNjHAVWL2qi6bVRW1ljROv07WWa59BaOe1jx68LlUmle3

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

INSERT INTO "public"."propositions" ("id", "proposition_id", "proposition_text", "search_queries") OVERRIDING SYSTEM VALUE VALUES
    (1, 'demo-prop', 'This is a demo proposition for testing purposes.', ARRAY['demo proposition', 'test proposition']),
    (2, 'marcos_robredo_2028', 'Bongbong Marcos and Leni Robredo will team up for the 2028 Philippine Presidential Election', ARRAY['BBM Leni Robredo','Marcos endorsement Kakampink','UniTeam split Robredo']),
    (3, 'sarah_duterte_wins_2028', 'Sara Duterte will win the 2028 Philippine Presidential Election', ARRAY['Sara Duterte 2028', 'Sara Duterte presidential bid', 'Sara Duterte election plans']);

--
-- Data for Name: sentiments; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "public"."sentiments" ("id", "proposition_id", "consensus_value", "attention_value", "rationale_consensus", "rationale_attention", "data_quality", "date_generated", "movement_analysis") OVERRIDING SYSTEM VALUE VALUES
	(1, 'demo-prop', 0.8, 0.6, 'The proposition has received moderate attention.', 'demo movement analysis', 0.9, '2024-06-01', 'The proposition is generally agreed upon.'),
	(2, 'marcos_robredo_2028', 0.28, 0.45, 'Both Marcos and Robredo explicitly denied discussing any 2028 alliance or political tandem, framing the meeting as non-political flood mitigation efforts, with media speculation from analysts met by skepticism and mockery from some partisan users rather than broad agreement.', 'The event prompted coverage from major outlets like Inquirer, Philstar, Bloomberg, and Business Mirror, alongside X posts from news accounts with thousands of views and dozens of engagements, making it a recognized political talking point today.', 0.85, '2026-02-22', 'Attention increased moderately from yesterday''s low chatter due to the high-profile Marcos-Robredo meeting in Naga City on flood projects, sparking speculation; consensus dipped slightly from polarization as official denials emphasized ''service first before politics,'' outweighing speculative support.'),
	(3, 'sarah_duterte_wins_2028', 0.5, 0.65, 'Duterte loyalists express strong belief in her victory, sharing articles on her achievements and declaring ''Sara for the win''; however, analysts describe her as ''winnable but not unbeatable'' amid impeachment threats and early announcement risks, maintaining a balanced divide.', 'The announcement sparked mainstream Philippine and international news coverage (e.g., Al Jazeera, Inquirer, ABS-CBN) alongside X posts with notable engagement (hundreds of likes on pro-Sara content), making it a prominent but not dominating topic.', 1, '2026-02-22', 'Attention increased due to Vice President Sara Duterte''s recent official announcement of her 2028 presidential bid, which generated news coverage and supporter buzz; consensus remained stable at polarization levels as reactions are mixed between enthusiastic support and cautious skepticism.'),
	(4, 'marcos_robredo_2028', 0.5, 0.55, 'Neutral reporting dominated with both leaders emphasizing ''service before politics'' and denying 2028 talks, while discourse split between excited pro-Robredo speculation and skeptical or mocking responses from other camps.', 'Mainstream Philippine news (Inquirer, Philstar, etc.) and some international coverage (Bloomberg) highlighted the Naga meeting, with X posts and videos gaining thousands of views and likes, marking it as a moderate talking point.', 1, '2026-02-22', 'Attention rose moderately from low levels due to President Marcos'' visit to Naga City and meeting with Mayor Leni Robredo, which fueled 2028 alliance speculation across news and social media; consensus stayed polarized as official denials balanced hopeful rumors.'),
	(5, 'sarah_duterte_wins_2028', 0.5, 0.75, 'Public discourse is deeply polarized with enthusiastic endorsements from Duterte loyalists, PDP-Laban support, and opinion pieces hailing her readiness, countered equally by administration downplaying, impeachment pushes, corruption accusations, and warnings of political jinxes or dynasty risks.', 'The topic dominates recent X posts and major news outlets like Inquirer, Manila Times, and Tribune with politician reactions, supporter rallies, and critic responses, indicating high virality post-announcement.', 0.9, '2026-02-22', 'Attention surged dramatically due to Sara Duterte''s official announcement of her 2028 presidential bid on February 18, 2026, sparking widespread reactions, while consensus held steady at polarization amid balanced pro and anti sentiments.'),
	(6, 'marcos_robredo_2028', 0.25, 0.75, 'Discourse overwhelmingly features Palace and opposition statements dismissing any political alliance or team-up for 2028, labeling it as non-political service visit; a tiny minority of users speculate or wish for Leni-Marcos tandem to counter Sara Duterte, but it''s heavily contextualized as unlikely.', 'Topic generated significant mainstream news coverage from Philstar, Inquirer, GMA, and ABS-CBN with thousands of views on X posts, plus viral chatter on the meeting, pink symbolism, and election rumors.', 0.9, '2026-02-19', 'Attention surged due to President Marcos'' high-profile visit to Naga City and meeting with Mayor Leni Robredo yesterday, fueling 2028 speculation; consensus decreased as official denials and opposition rejections dominated over fringe tandem suggestions.'),
	(7, 'sarah_duterte_wins_2028', 0.5, 0.1, 'Public opinion remains perfectly polarized, with Duterte loyalists seeing her as an early frontrunner amid her recent bid announcement, countered by strong opposition highlighting impeachment threats, budget scandals, and political rifts.', 'Extremely low chatter on X with zero recent posts retrieved since February 21 despite targeted searches, though some news coverage persists on her running mate recruitment.', 0.6, '2026-02-19', 'Scores did not move compared to yesterday due to lack of significant new discourse or viral activity, with only minor news on her running mate failing to generate buzz.'),
	(8, 'marcos_robredo_2028', 0.25, 0.75, 'Rumors of a Marcos endorsement for Robredo circulate due to the Naga meeting for flood projects, but Malacañang deems it ''untimely'' and Marcos prioritizes service over politics; X posts reflect partisan skepticism, past election grievances, and mockery rather than broad acceptance of a team-up.', 'High virality evidenced by multiple recent mainstream news articles (ABS-CBN, GMA, Inquirer) and political X discussions on the Naga visit fueling 2028 speculation, though individual post engagements are moderate.', 0.8, '2026-02-20', 'Scores remained stable as today''s data shows continued speculation from Marcos'' recent Naga visit meeting Leni Robredo, but no major shift in sentiment or volume surge beyond yesterday''s levels.'),
	(9, 'sarah_duterte_wins_2028', 0.6, 0.75, 'Supporters express strong confidence in her victory based on high SWS satisfaction ratings (+28 net, highest among officials) and regional strongholds, while opposition highlights challenges in expanding to Luzon and developing policy platforms, yielding broad but not unanimous support.', 'Extensive mainstream and international media coverage (BBC, Al Jazeera, AP, Inquirer) plus X posts with thousands of views and hashtags like #SaraDuterte2028 demonstrate high virality across platforms.', 0.9, '2026-02-20', 'Attention surged dramatically from low chatter yesterday due to the fresh wave of news coverage on Sara Duterte''s 2028 presidential announcement, while consensus edged slightly higher from perfect polarization as pro-Duterte enthusiasm citing polls outweighed critiques.'),
	(10, 'marcos_robredo_2028', 0.3, 0.75, 'Discourse dominated by Malacañang and Marcos denials framing the meeting as non-political service work, with partisan opposition from DDS and hardcore Kakampinks; a minority of analysts and excited users defend potential tandem as strong vs. Sara, but no broad acceptance it''s happening.', 'High virality evidenced by coverage across major outlets like Philstar, ABS-CBN, GMA, and X posts from influencers like Jervis Manahan and Richard Heydarian garnering 100s of likes and 10k+ views.', 0.9, '2026-02-21', 'Consensus slightly increased from 0.25 due to speculative support from analysts and some netizens post-Naga meeting, but remains low amid strong official denials; attention stable at 0.75 as media coverage and social buzz persist.'),
	(11, 'sarah_duterte_wins_2028', 0.68, 0.85, 'Pro-Sara narratives dominate with mentions of her highest SWS satisfaction rating (+28, up 6 pts) and early poll leads, portraying 2028 as inevitable; opposition highlights strategic flaws like weak Luzon appeal and impeachment risks, but with lower engagement.', 'High virality evidenced by international news coverage (BBC, Reuters, Al Jazeera), local outlets (Manila Times, Philstar), and X posts with up to 6,300 views, 253 likes, amid her bid announcement.', 0.9, '2026-02-21', 'Both scores ticked up slightly from yesterday due to sustained buzz from Sara Duterte''s recent presidential bid announcement, positive poll references, and media coverage.'),
	(12, 'marcos_robredo_2028', 0.45, 0.35, 'Official statements from Malacañang and Marcos dismiss rumors of political alliance or endorsement as ''untimely'' or non-political, with only minority analyst speculation suggesting potential viability; overall neutral reporting with skepticism prevails over agreement.', 'Multiple mainstream Philippine news outlets (ABS-CBN, Inquirer, GMA, Sunstar) reported on the Naga meeting and rumors today, but no significant X/Twitter discussion found despite searches.', 0.7, '2026-01-15', 'Attention increased moderately due to recent news coverage of President Marcos'' visit to Naga City and meeting with Leni Robredo, sparking 2028 alliance rumors, while consensus dipped slightly amid official denials.'),
	(13, 'sarah_duterte_wins_2028', 0.7, 0.75, 'Recent polls (e.g., WR Numero with 33.3% support, leading by 16 points in others) position her as the frontrunner, indicating broad public support for her potential victory, though opposition persists amid impeachment efforts and criticisms of her early bid.', 'The topic dominates headlines with coverage from BBC, Al Jazeera, Reuters, and local outlets like Inquirer and ABS-CBN following her bid announcement four days ago, signaling high virality.', 0.8, '2026-01-15', 'Attention surged dramatically due to Sara Duterte''s recent announcement of her 2028 presidential bid, covered widely by international and local media; consensus increased modestly as polls show her leading voter preferences.'),
	(14, 'marcos_robredo_2028', 0.25, 0.5, 'News reports highlight denials from the Marcos camp calling an endorsement ''untimely'' and Marcos dismissing rumors of courting Robredo, with Robredo emphasizing service over politics; no observed public support or enthusiasm for the unlikely team-up given their 2022 rivalry.', 'Multiple major Philippine news outlets like Inquirer, GMA, ABS-CBN, and PhilStar ran stories in the last 1-3 days on Marcos'' Naga visit sparking 2028 speculation, indicating a recognized talking point though social media volume was undetectable.', 0.6, '2026-01-16', 'Attention increased due to recent news coverage of President Marcos'' visit to Naga City amid 2028 team-up rumors, while consensus decreased as officials from both sides firmly dismissed any political alliance.'),
	(15, 'sarah_duterte_wins_2028', 0.75, 0.8, 'Recent polls like Tangere survey show Sara Duterte leading with 43% voter preference far ahead of others, indicating broad public support for her as a likely winner despite vocal criticism from Marcos administration allies and impeachment issues.', 'High volume of recent articles from major outlets like Inquirer, ABS-CBN, BBC, and Al Jazeera on her presidential bid announcement, running mate hints, and political reactions demonstrate sustained high virality across news platforms.', 0.9, '2026-01-16', 'Scores remained largely stable compared to yesterday, with attention slightly increasing due to fresh coverage of Sara Duterte''s running mate recruitment amid sustained post-announcement buzz, while consensus held steady supported by recent polls confirming her frontrunner status.'),
	(16, 'marcos_robredo_2028', 0.25, 0, 'No evidence of current agreement or disagreement; searches returned no relevant discussions supporting or refuting the BBM-Leni team-up, enforcing default to yesterday''s strong opposition score per low attention rule.', 'Multiple X keyword and semantic searches plus web searches yielded zero recent (since Feb 2026) results specifically on the proposition, confirming complete lack of discourse.', 0.1, '2026-01-17', 'Attention drastically decreased from moderate levels yesterday to utter silence today with no recent posts or news found; consensus defaulted to yesterday''s value due to low attention.'),
	(17, 'sarah_duterte_wins_2028', 0.75, 0.85, 'Duterte supporters on X hail her as ''future President'' with images of crowds and positive events, and one post notes her leading 2028 polls; opposition cites impeachment efforts, Marcos feud, and pro-China allegations, reflecting broad support tempered by vocal minority dissent.', 'Extensive mainstream coverage from BBC, Al Jazeera, NHK, Inquirer, and ABS-CBN on her 2028 bid announcement, feud, and running mate tease, coupled with recent X posts on her activities and political drama.', 0.9, '2026-01-17', 'Attention increased slightly due to fresh news on Sara Duterte''s recruited running mate amid ongoing post-announcement buzz, while consensus held steady with balanced pro-Duterte enthusiasm and opposition criticism similar to yesterday.'),
	(18, 'marcos_robredo_2028', 0.25, 0.25, 'Reports highlight rumors of potential team-up or endorsement triggered by President Marcos'' visit to Leni Robredo''s Naga City, but Malacañang and Marcos himself dismissed it as non-political service delivery, with no observed public endorsement or agreement.', 'Topic received coverage in major Philippine news outlets like ABS-CBN, Inquirer, GMA, and SunStar within the last 1-2 days, but searches yielded no relevant X/Twitter posts indicating low social media volume.', 0.5, '2026-01-18', 'Attention increased slightly due to recent news coverage of Marcos'' visit to Naga City sparking brief 2028 alliance rumors, while consensus remained unchanged amid official denials.'),
	(19, 'sarah_duterte_wins_2028', 0.78, 0.9, 'Recent Tangere poll (Feb 19-20, 2026) shows Sara Duterte leading with 43% support, 16 points ahead of closest rival, indicating broad acceptance as frontrunner despite vocal opposition from Marcos allies amid their feud.', 'High volume of mainstream news coverage (BBC, Al Jazeera, AP, Inquirer, ABS-CBN) on her 2028 bid announcement four days ago, plus fresh poll results dominating political discourse.', 0.85, '2026-01-18', 'Attention increased due to Sara Duterte''s recent presidential bid announcement and new polls confirming her lead, while consensus remained stable around broad support levels from yesterday.'),
	(20, 'marcos_robredo_2028', 0.25, 0.35, 'Speculation about a Marcos endorsement for Robredo exists in news reports following the Naga visit, but Palace deems it ''untimely'' and Marcos insists it''s non-political; past 2022 rivalry suggests strong public skepticism or opposition to any team-up.', 'Multiple mainstream Philippine news outlets (GMA, ABS-CBN, Philstar, Inquirer) published articles in the last 1-3 days on the rumors, indicating moderate discussion, though no significant X/Twitter volume was retrieved.', 0.7, '2026-01-19', 'Attention slightly increased due to recent news coverage of President Marcos'' Naga City visit to Leni Robredo''s turf sparking endorsement rumors, while consensus remained stable amid official denials.'),
	(21, 'sarah_duterte_wins_2028', 0.75, 0.85, 'Sara Duterte''s recent presidential bid announcement positions her as a frontrunner in media reports, supported by her political legacy, but countered by vocal social media opposition citing corruption scandals like DPWH leaks and fears of releasing scam convicts if she wins.', 'Extensive mainstream and international news coverage (BBC, Al Jazeera, ABS-CBN, Inquirer) in the past 4 days, including updates as recent as 20 hours ago, signals high virality and national discussion.', 0.8, '2026-01-19', 'Attention slightly decreased from yesterday''s peak as the initial buzz around Sara Duterte''s Feb 18 announcement settles, while consensus held steady without major shifts in sentiment.'),
	(22, 'marcos_robredo_2028', 0.25, 0.3, 'Recent news reports rumors of a Marcos-Robredo alliance for 2028 due to their Feb 21 meeting, but Marcos dismissed any courting, and there''s no broad public agreement or enthusiasm—only isolated analyst speculation amid ongoing political rivalries.', 'Low chatter on X with no recent posts matching queries since Feb 21; attention limited to a handful of news articles on the Naga meeting and dismissed 2028 rumors.', 0.6, '2026-01-20', 'Scores remained largely stable compared to yesterday, with a slight dip in attention as X discourse was minimal despite recent news on a Marcos-Robredo meeting sparking minor 2028 rumors.'),
	(23, 'sarah_duterte_wins_2028', 0.78, 0.95, 'Recent polls such as Tangere (43% preference), Manila Times (16 points ahead of Leni Robredo), and ongoing WR Numero surveys show Sara Duterte consistently leading by wide margins, indicating broad support for her winning the 2028 election despite vocal anti-Duterte sentiment from activists on X.', 'The proposition is at national dominance level with extensive mainstream and international coverage (BBC, Al Jazeera, Diplomat) of her candidacy declaration, running mate recruitment, and new polls, making it the central political topic.', 0.9, '2026-01-20', 'Attention increased from 0.85 to 0.95 due to Sara Duterte''s official presidential bid announcement four days ago and fresh poll releases today confirming her lead, while consensus slightly rose from 0.75 reflecting poll consistency without major shifts.'),
	(24, 'marcos_robredo_2028', 0.25, 0.4, 'Discourse centers on Marcos'' Naga visit to Leni Robredo for flood relief, with Palace and Marcos insisting ''no politics'' and dismissing 2028 alliance rumors as untimely; a few analysts speculate on possible endorsement but no broad agreement or enthusiasm for the proposition.', 'Major Philippine news outlets like Inquirer, GMA, and ABS-CBN published articles today on the meeting and speculation, indicating moderate discussion, though X searches yielded no recent matching posts.', 0.7, '2026-01-21', 'Attention slightly increased due to recent Marcos-Robredo meeting in Naga sparking 2028 speculation in news, while consensus remained stable amid official denials.'),
	(25, 'sarah_duterte_wins_2028', 0.82, 0.97, 'Recent Tangere survey places Sara Duterte at 43% voter preference, leading early 2028 polls, signaling broad support from her loyal base despite vocal anti-Duterte sentiment on X and ongoing plunder complaints.', 'High volume of recent coverage from major outlets like BBC, Al Jazeera, AP, and local news on her presidential bid announcement, polls, and feud with Marcos.', 0.9, '2026-01-21', 'Consensus edged up slightly with new polls reaffirming her lead as frontrunner, while attention stayed near peak levels due to sustained media coverage of her announcement and related developments.'),
	(26, 'marcos_robredo_2028', 0.25, 0.25, 'Official statements from Marcos and Robredo explicitly deny any political discussions or 2028 alliance plans during their recent Naga meeting, with opposition figures opposing the idea and only isolated analyst speculation in favor; public discourse treats it as untimely rumor given historical rivalry.', 'Topic appears in several mainstream Philippine news outlets due to President Marcos'' February 21 visit to Naga City sparking brief 2028 team-up rumors, but no matching recent X posts found indicating minimal social media volume.', 0.6, '2026-01-22', 'Attention decreased from moderate-low to low chatter as social media shows no recent posts despite news coverage of Marcos'' Naga visit; consensus remained stable amid official denials reinforcing skepticism.'),
	(27, 'sarah_duterte_wins_2028', 0.85, 0.9, 'Recent opinion polls from sources like Manila Times and others position Sara Duterte as the frontrunner for 2028, with significant leads, reflecting broad acceptance of her viability despite vocal opposition and scandals.', 'The topic dominates headlines with her Feb 18 presidential bid announcement covered by BBC, Al Jazeera, AP, and local outlets like Inquirer and ABS-CBN, plus new poll releases ensuring high virality.', 0.9, '2026-01-22', 'Consensus slightly increased due to new polls confirming Sara Duterte''s lead in early 2028 surveys, while attention dipped marginally from peak post-announcement but remains high amid ongoing media coverage.'),
	(28, 'marcos_robredo_2028', 0.25, 0, 'Absence of any supportive, neutral, or even speculative mentions of a BBM-Leni team-up; searches returned unrelated opposition unity talks (e.g., Leni-Kiko reunion) or none at all, justifying continuation of strong opposition.', 'No X posts or web results discussing the proposition or related queries on February 22, 2026, despite BBM''s recent visit to Leni''s city.', 0.2, '2026-01-23', 'No change in consensus due to low attention defaulting to yesterday''s score; attention dropped from low chatter to complete silence with no mentions of the proposition today.'),
	(29, 'sarah_duterte_wins_2028', 0.85, 0.85, 'Recent polls like Tangere (43% preference post-announcement) and Manila Times (16-point lead over rivals) indicate broad support and positioning as the favorite to win 2028, despite some past opposition and impeachment talks.', 'High volume of mainstream news coverage (BBC, Al Jazeera, Inquirer, ABS-CBN within last 24 hours) and new polls confirm significant virality and discussion around her bid.', 0.9, '2026-01-23', 'Scores remained stable compared to yesterday as Sara Duterte''s recent presidential bid announcement and leading poll results sustain high public interest and perceived frontrunner status without major shifts.'),
	(30, 'marcos_robredo_2028', 0.25, 0.25, 'Speculation arose from Marcos'' Naga visit and interaction with Robredo, but Palace called endorsement ''untimely,'' Marcos stressed service over politics, and no evidence of public buy-in given their 2022 rivalry; only niche speculation without support.', 'Several recent news articles from ABS-CBN, Inquirer, and GMA discuss the rumors tied to the Naga event, but X searches yielded no relevant posts, suggesting low social media chatter.', 0.5, '2026-01-24', 'Attention increased slightly from 0.0 due to President Marcos'' recent visit to Naga City sparking media speculation about a 2028 tandem, while consensus held steady at strong opposition as rumors were promptly dismissed.'),
	(31, 'sarah_duterte_wins_2028', 0.82, 0.9, 'Recent Tangere poll (Feb 19-20, 2026) shows Sara Duterte leading with 43% voter preference, indicating broad support as frontrunner, though opposition figures like Trillanes urge unity to defeat her and highlight accountability issues.', 'Her Feb 18 announcement of presidential bid received extensive coverage from international outlets like BBC, Al Jazeera, AP, and local news, dominating political discourse with poll discussions.', 0.85, '2026-01-24', 'Consensus slightly decreased from 0.85 due to increased opposition calls to unite against her amid impeachment threats, while attention increased slightly from 0.85 boosted by her recent presidential bid announcement.'),
	(32, 'marcos_robredo_2028', 0.25, 0.35, 'Leaders from both sides, including Marcos and Robredo, explicitly denied any political discussions or 2028 team-up during their meeting, calling rumors untimely or a disservice to public service; limited speculation from analysts represents a tiny minority.', 'Several mainstream news articles (ABS-CBN, Inquirer, GMA, SunStar) covered the rumors post-Naga visit, but searches yielded no recent viral X posts, indicating low social media volume.', 0.7, '2026-01-25', 'Attention slightly increased due to recent Naga City meeting between Marcos and Robredo sparking rumor coverage in news media, while consensus stable amid firm denials from officials.'),
	(33, 'sarah_duterte_wins_2028', 0.85, 0.95, 'Sara Duterte leads early 2028 presidential polls with 43% voter preference in recent Tangere survey and dominates pre-election surveys per Wikipedia, reflecting broad agreement on her frontrunner status despite opposition calls to unite against her.', 'Major news coverage from BBC, Al Jazeera, AP News, Inquirer, and others on her presidential run announcement 4 days ago and hints at a running mate indicate high virality and national political focus.', 0.9, '2026-01-25', 'Consensus slightly increased and attention remained high following VP Sara Duterte''s announcement of her 2028 presidential bid and new polls affirming her lead, sustaining yesterday''s strong sentiment.'),
	(34, 'marcos_robredo_2028', 0.25, 0.25, 'Official Palace and Marcos statements dismiss endorsement or alliance rumors as ''untimely'' or apolitical, reflecting strong opposition to the proposition amid historical 2022 rivalry; only niche analysts speculate on potential benefits like Robredo beating Duterte with Marcos backing.', 'Low chatter limited to a handful of recent news articles on the Naga visit sparking 2028 rumors, with no significant or viral discussion found on X/Twitter.', 0.6, '2026-01-26', 'Scores stable compared to yesterday; brief news speculation from Marcos''s recent Naga visit did not gain traction on social media or lead to broader public discourse.'),
	(35, 'sarah_duterte_wins_2028', 0.85, 0.85, 'Sara Duterte consistently leads in the latest available polls (e.g., 31.4% in WR Numero Aug 2025), with opposition leaders calling for unity to rival her and media questioning if she is unbeatable, indicating broad acceptance of her as the likely winner despite impeachment threats and political feuds.', 'High volume of recent mainstream news coverage from BBC, Al Jazeera, Inquirer, and ABS-CBN on her 2028 bid and running mate recruitment, combined with active political discussions on X reflecting the feud with Marcos.', 0.9, '2026-01-26', 'Scores remained largely stable compared to yesterday, with attention slightly decreasing as the initial buzz from Sara Duterte''s presidential bid announcement four days ago normalizes, while consensus holds firm due to her established frontrunner status.'),
	(36, 'marcos_robredo_2028', 0.25, 0.25, 'Official statements deny any political intent behind the recent Naga meeting between Marcos and Robredo, dismissing 2028 alliance rumors; no evidence of public support or acceptance of a team-up, consistent with strong opposition.', 'Coverage limited to a handful of news articles on yesterday''s work-related meeting, with zero relevant discussions found on X despite targeted searches.', 0.4, '2026-01-27', 'Scores remained stagnant as recent news of a Marcos-Robredo meeting was explicitly clarified as non-political, mirroring yesterday''s low agreement and chatter without new developments sparking change.'),
	(37, 'sarah_duterte_wins_2028', 0.9, 0.95, 'Early polls post-announcement (Tangere Feb 19-20: 43%; Manila Times: 16-pt lead) position Sara Duterte as the clear frontrunner, reflecting broad support amid her feud with Marcos, though vocal opposition labels her pro-China.', 'The topic dominates with international news coverage (BBC, Al Jazeera), Wikipedia updates, recent polls, and polarized X discussions, marking high virality following her bid declaration.', 0.9, '2026-01-27', 'Scores increased slightly due to Sara Duterte''s recent presidential bid announcement on Feb 18 and new polls confirming her strong lead, boosting both agreement on her frontrunner status and discussion volume.'),
	(38, 'marcos_robredo_2028', 0.25, 0.3, 'The proposition faces strong skepticism as Malacañang labels alliance talks ''untimely'' and non-political, with Robredo avoiding confirmation; only niche speculation from analysts and fans exists without broad support.', 'Low-to-moderate volume with several recent news articles from ABS-CBN, Rappler, and Inquirer on the Marcos-Robredo meeting and pink socks anecdote, but negligible relevant discussions on X/Twitter.', 0.6, '2026-01-28', 'Attention saw a slight increase from yesterday due to news coverage of President Marcos'' visit to Naga City Mayor Leni Robredo, sparking brief speculation, while consensus stayed stable amid official dismissals of any political alliance.'),
	(39, 'sarah_duterte_wins_2028', 0.88, 0.9, 'Recent Tangere survey shows Sara Duterte leading 2028 presidential preferences at 43%, with Wikipedia noting she dominates early polls alongside Bong Go; despite Marcos feud and impeachment threats, no strong rejection observed, indicating broad support from her base.', 'High volume of recent news coverage from BBC, Al Jazeera, Inquirer, ABS-CBN, and others on her announcement, running mate recruitment, and polls, maintaining significant political discourse.', 0.9, '2026-01-28', 'Scores remained largely stable compared to yesterday, with consensus holding strong due to confirming polls and attention slightly dipping as the announcement hype from 4 days ago begins to normalize.'),
	(40, 'marcos_robredo_2028', 0.25, 0, 'No current discourse on the proposition found across X or web searches, resulting in default to yesterday''s consensus score of 0.25 amid negligible attention.', 'Utter silence with zero relevant posts on X (including latest and semantic searches) and no pertinent news or mentions in web results for recent dates.', 0.1, '2026-01-29', 'Attention dropped to zero due to complete absence of any mentions or discussions today; consensus held steady at yesterday''s level per low-attention default rule.'),
	(41, 'sarah_duterte_wins_2028', 0.86, 0.85, 'Sara Duterte leads early pre-election polls and is seen as a strong frontrunner by lawmakers and analysts, with broad acceptance of her winnability despite vocal opposition from Marcos allies and questions on her strategy.', 'High volume of recent news coverage across major Philippine outlets (Inquirer, ABS-CBN) and international media (BBC, Al Jazeera) on her 2028 bid announcement and running mate recruitment, though limited recent X discourse.', 0.9, '2026-01-29', 'Scores slightly decreased from yesterday due to emerging criticisms of her early bid timing and impeachment shadows, but remained high amid ongoing media buzz without major new events.'),
	(42, 'marcos_robredo_2028', 0.25, 0.25, 'All retrieved news sources report the Marcos-Robredo meeting as strictly for flood response and public service, with both parties denying any political agenda or 2028 election talks; no sources or social posts endorse or seriously entertain the proposition of them teaming up.', 'Topic received low-moderate mainstream news coverage around the recent Naga visit but no detectable volume on X/Twitter despite multiple searches.', 0.6, '2026-01-30', 'Attention increased slightly due to news coverage of President Marcos'' visit to Naga City Mayor Leni Robredo on Feb 21, but consensus remained stable as the meeting was explicitly described as non-political with no team-up discussions.'),
	(43, 'sarah_duterte_wins_2028', 0.87, 0.95, 'Discourse highlights her massive 32 million votes from 2022 haunting rivals, endorsements from groups like 1Bangsa, and neutral response from PBBM, indicating broad support and acceptance as a strong contender despite vocal opposition alarms over timing and controversies.', 'The announcement dominated recent news cycles with multiple articles from PNA, Business Mirror, Tribune, and others published in the last 3 days, alongside X discussions tying it to impeachment clearance, marking high virality.', 0.9, '2026-01-30', 'Attention surged due to Vice President Sara Duterte''s recent official announcement of her 2028 presidential bid, while consensus saw a minor increase as it reinforces her frontrunner status amid supportive narratives.'),
	(44, 'marcos_robredo_2028', 0.25, 0.4, 'Leaders Marcos and Robredo explicitly dismissed political discussions during the Naga visit, calling rumors of a 2028 alliance premature and focusing on flood control; while one analyst speculated a Marcos-endorsed Robredo could defeat rivals, this represents only a tiny, unendorsed minority view against widespread neutral-to-skeptical reporting.', 'Multiple mainstream Philippine news sources (GMA, Inquirer, Sunstar) published stories today on the Naga visit and 2028 speculation, indicating moderate discussion as a recognized talking point, though no significant X/Twitter chatter was found.', 0.7, '2026-01-31', 'Attention increased moderately due to President Marcos''s recent visit to Naga City—where Leni Robredo is mayor—sparking rumors of a 2028 team-up in mainstream news outlets; consensus remained stable amid firm denials from both leaders emphasizing service over politics.'),
	(45, 'sarah_duterte_wins_2028', 0.85, 0.85, 'Recent polls and surveys position Sara Duterte as the frontrunner for 2028, leading rivals like Leni Robredo by 16 points, suggesting broad agreement on her strong chances despite vocal opposition amid Marcos feud and impeachment threats.', 'Topic sustains high visibility through mainstream news from BBC, Al Jazeera, Inquirer, and ABS-CBN on her bid and running mate, though recent X/Twitter searches yielded no results indicating possibly cooling social chatter.', 0.8, '2026-01-31', 'Slight decrease from yesterday''s peaks as the initial buzz from Sara Duterte''s announcement four days ago settles into more detailed coverage like her running mate recruitment, without new major escalations.'),
	(46, 'marcos_robredo_2028', 0.25, 0.45, 'Major news outlets report rumors of a potential Marcos endorsement for Robredo fueled by the Naga visit and optics like pink socks, but Palace and Robredo firmly deny any political discussions, with only fringe analysts entertaining the idea amid historical rivalry.', 'Moderate coverage in Philippine mainstream news (Inquirer, GMA, ABS-CBN) on the recent event, but minimal to no recent X posts indicate low social media virality.', 0.7, '2026-02-01', 'Attention slightly increased due to Marcos'' recent visit to Naga City (Robredo''s base) sparking media rumors of a 2028 alliance, while consensus remained stable amid consistent skepticism.'),
	(47, 'sarah_duterte_wins_2028', 0.87, 0.92, 'Early opinion polls from Tangere and Manila Times show VP Sara Duterte leading her closest rival by 16 points in 2028 presidential preference, indicating broad support amid her official bid announcement, despite vocal opposition and impeachment discussions.', 'High volume of recent coverage from BBC, Al Jazeera, AP, Inquirer, and Wikipedia updates on her presidential run and leading polls demonstrates national dominance in political discourse.', 0.9, '2026-02-01', 'Consensus slightly increased due to new early polls showing Sara Duterte leading by 16 points, while attention rose with ongoing media coverage of her announcement and poll results compared to yesterday.'),
	(48, 'marcos_robredo_2028', 0.25, 0.55, 'Both Marcos and Robredo insisted the meeting was solely about flood control and infrastructure funding with no political discussion; palace deems endorsement talk ''untimely,'' reinforcing strong skepticism and rejection of the proposition amid historical rivalry.', 'Several major Philippine news outlets like Inquirer, GMA, and ABS-CBN ran stories today on the Naga meeting and related speculation, marking it as a moderate talking point, though X searches yielded no significant posts.', 0.7, '2026-02-02', 'Attention slightly increased due to mainstream news coverage of Marcos'' Naga visit with Robredo sparking 2028 team-up rumors, while consensus held steady amid official denials emphasizing non-political intent.'),
	(49, 'sarah_duterte_wins_2028', 0.84, 0.93, 'Supporters portray Sara Duterte as an underdog whose popularity surges amid attacks, with calls like ''President Sara Duterte 2028''; opposition like Risa Hontiveros claims a united front can defeat her, indicating broad but not unanimous agreement on her frontrunner viability.', 'High volume of recent X posts from news outlets and influencers with thousands of views/engagements, plus international and local news coverage (BBC, AP, Al Jazeera) on her presidential bid announcement and impeachments.', 0.85, '2026-02-02', 'Scores remained largely stable compared to yesterday, with a slight dip in consensus due to fresh impeachment filings and opposition rhetoric, offset by pro-Duterte narratives framing attacks as beneficial to her campaign.'),
	(50, 'marcos_robredo_2028', 0.25, 0.65, 'Official Palace and Marcos statements repeatedly dismiss alliance or endorsement talks as ''premature,'' ''untimely,'' and ''strictly work-related''; speculation exists among some analysts and social media users as a potential counter to Sara Duterte, but it is portrayed as baseless rumor with no affirmative support or agreement observed.', 'Mainstream news outlets like ABS-CBN, GMA, Inquirer, and Rappler prominently cover the Naga meeting and 2028 speculation, with Facebook posts and videos amplifying the buzz over the past few days.', 0.7, '2026-02-03', 'Attention increased moderately due to President Marcos'' recent visit to Naga City Mayor Leni Robredo sparking widespread rumors of a 2028 alliance, while consensus remained stable amid strong official denials.'),
	(51, 'sarah_duterte_wins_2028', 0.85, 0.65, 'Recent polls from Manila Times and others show Sara Duterte leading by significant margins in early 2028 presidential preference surveys, supporting broad agreement she is positioned to win, though opposition like Risa Hontiveros claims a united front can defeat her amid corruption allegations.', 'High visibility in major news outlets (BBC, Al Jazeera, Inquirer) following her recent presidential bid announcement and running mate recruitment, coupled with poll discussions, but no new X posts matching key queries today indicates waning social media volume.', 0.9, '2026-02-03', 'Consensus slightly increased due to new polls confirming Sara Duterte''s lead in early 2028 surveys; attention decreased as X chatter dropped off today despite ongoing news coverage.'),
	(52, 'marcos_robredo_2028', 0.25, 0.45, 'Official statements from Malacañang and Marcos dismiss any 2028 political alliance or endorsement as ''untimely'' and non-political, with rumors treated as mere speculation rather than likely reality; a tiny minority of analysts and social posts entertain the idea positively but face broad skepticism.', 'Recent mainstream news coverage (ABS-CBN, Inquirer, GMA) on the Feb 20-21 Marcos-Robredo meeting fueled short-term speculation, but zero matching recent X posts indicate low ongoing social virality.', 0.6, '2026-02-04', 'Attention decreased slightly from yesterday''s higher buzz following Marcos'' Naga visit, as no new developments emerged today and X showed no recent posts; consensus stable at strong skepticism.'),
	(53, 'sarah_duterte_wins_2028', 0.82, 0.88, 'Recent Tangere poll (Feb 19-20, 2026) positions Sara Duterte as the frontrunner with 43% voter preference and a 16-point lead, indicating broad support rooted in Duterte legacy, though vocal opposition (e.g., Risa Hontiveros, Makabayan bloc) pushes impeachment and anti-Duterte strategies.', 'Discourse dominates with international/regional news (BBC, Al Jazeera, Reuters), Philippine outlets reporting her bid/running mate/polls, and high-engagement X posts debating her electability and opposition plans.', 0.9, '2026-02-04', 'Attention increased significantly from yesterday due to ongoing buzz from Sara Duterte''s Feb 18 presidential bid announcement, new leading polls, and running mate hints, while consensus slightly decreased amid heightened opposition impeachment narratives and unity calls.'),
	(54, 'marcos_robredo_2028', 0.25, 0.5, 'Recent news highlights rumors of potential endorsement or alliance sparked by President Marcos'' visit to Naga City Mayor Leni Robredo for flood control inspection, including a symbolic pink socks gesture, but both leaders explicitly denied any political discussions or team-up intentions, emphasizing service over politics amid Sara Duterte''s 2028 bid announcement.', 'Moderate discussion driven by mainstream Philippine news outlets (GMA, ABS-CBN, Philstar) reporting on the Naga visit and resulting 2028 speculation, though social media chatter appears low.', 0.6, '2026-02-05', 'Consensus unchanged at strong opposition due to persistent denials; attention stable as news coverage of Marcos'' Naga visit maintained moderate volume without escalation.'),
	(55, 'sarah_duterte_wins_2028', 0.83, 0.89, 'Recent polls like Tangere (Feb 19-20, 2026) show Sara Duterte leading at 43%, positioning her as the frontrunner with strong Duterte base support, though tempered by impeachment threats and opposition unity calls.', 'Topic dominates Philippine news outlets (Inquirer, ABS-CBN) and international media (BBC, Al Jazeera, Reuters) with fresh updates on her bid declaration and running mate recruitment.', 0.9, '2026-02-05', 'Scores showed minimal movement with attention slightly up due to new statements on her running mate, while consensus held steady amid ongoing poll leads and impeachment discussions.'),
	(56, 'marcos_robredo_2028', 0.25, 0.55, 'Speculation of a Marcos-Robredo alliance or endorsement for 2028 emerged from their recent Naga meeting, but Palace deemed it ''untimely,'' Marcos dismissed courting rumors, and social posts show opposition reunions rather than unity with administration, indicating strong skepticism.', 'Multiple mainstream Philippine news outlets (Inquirer, ABS-CBN, GMA, SunStar) published articles within the last 2 days on the meeting and 2028 rumors, but X/Twitter shows limited recent posts, suggesting moderate rather than viral discussion.', 0.7, '2026-02-06', 'Attention slightly increased due to recent news coverage of President Marcos'' visit to Naga City and meeting with Mayor Leni Robredo sparking endorsement rumors, but consensus held steady amid official dismissals and lack of social endorsement.'),
	(57, 'sarah_duterte_wins_2028', 0.84, 0.82, 'Early polls and surveys position Sara Duterte as the frontrunner for 2028, with analysts noting her strong Duterte base and the need for unified opposition to challenge her; supporters frame impeachment efforts as politically motivated attacks amid her feud with Marcos.', 'High volume of recent news articles on her announcement and polls, coupled with social media discussions on impeachment and 2028 strategies, indicate sustained but not peak virality.', 0.85, '2026-02-06', 'Scores slightly decreased from yesterday as the initial buzz from Sara Duterte''s recent presidential bid announcement settles without major new developments today.'),
	(58, 'marcos_robredo_2028', 0.25, 0.6, 'Public discourse shows speculation from analysts about Marcos possibly endorsing Robredo against Sara Duterte in 2028, but Palace explicitly denied any politicking or alliance discussions as ''too early''; social media mentions are sarcastic or dismissive, viewing a team-up as unlikely or career-ending for Leni.', 'Moderate buzz from recent news coverage of Marcos'' Naga visit and analyst opinions, but limited high-engagement X posts directly on the proposition indicates it''s a niche talking point rather than widespread virality.', 0.7, '2026-02-07', 'Attention slightly increased due to President Marcos'' recent visit to Naga City where Leni Robredo is mayor, sparking media speculation about potential endorsement, while consensus remained stable amid dismissals and mocking tones.'),
	(59, 'sarah_duterte_wins_2028', 0.81, 0.75, 'Broad support persists among her strong base in Visayas and Mindanao, with vocal endorsements framing her as the inevitable winner despite impeachments; opposition highlights her early bid as potentially advantageous to rivals and ties it to impeachment fears, maintaining high polarization short of strong rejection.', 'High virality continues with recent mainstream news coverage (e.g., ABS-CBN on running mate recruitment 20 hours ago, PBBM comments, international outlets like BBC/Al Jazeera) on her 2028 bid announcement, though X-specific chatter appears low today.', 0.75, '2026-02-07', 'Both scores slightly decreased from yesterday as the intense buzz from Sara Duterte''s presidential bid announcement four days ago begins to subside without major new developments today.'),
	(60, 'marcos_robredo_2028', 0.25, 0.65, 'Discourse centers on rumors sparked by Marcos and Robredo''s Naga meeting, but President Marcos explicitly dismissed any courting or political team-up for 2028; a minor analyst suggested BBM endorsement for Leni could beat Sara, but this is fringe and heavily doubted.', 'Several mainstream Philippine news outlets (SunStar, Politiko, Manila Bulletin, etc.) published articles today and yesterday on the meeting and rumors, indicating moderate volume, though X/Twitter shows negligible native discussion.', 0.7, '2026-02-08', 'Attention slightly increased due to fresh news coverage of Marcos dismissing 2028 alliance rumors after their recent Naga City meeting, while consensus remains unchanged amid official denials reinforcing skepticism.'),
	(61, 'sarah_duterte_wins_2028', 0.82, 0.95, 'Recent non-commissioned polls such as Tangere show Sara Duterte leading with 43% voter preference, dominating early surveys; enthusiastic supporter posts declare her the inevitable winner, though opposition highlights impeachment risks and targets her as the main threat.', 'The topic dominates Philippine news with international coverage from BBC, Al Jazeera, and local outlets like Inquirer and ABS-CBN reporting on the announcement, running mate recruitment, and political reactions in the last few days.', 0.9, '2026-02-08', 'Attention surged due to Sara Duterte''s recent official announcement of her 2028 presidential bid and updates on her running mate, while consensus remained stable as new polls reaffirm her leading position.'),
	(72, 'marcos_robredo_2028', 0.22, 0.45, 'Speculation of a Marcos endorsement or alliance with Robredo for 2028 emerged from their Feb 21 meeting in Naga, but official statements emphasize ''service before politics'' and deem it ''untimely,'' with no broad public support or acceptance observed; X posts show no affirmative discourse on team-up.', 'Moderate coverage in mainstream news (GMA, Inquirer, ABS-CBN) on the meeting and rumors, but negligible recent X activity indicates low virality beyond niche political circles.', 0.6, '2026-02-14', 'Scores slightly decreased as rumors from Marcos-Robredo Naga meeting were quickly dismissed by the Palace, reducing momentum from yesterday''s higher attention without sparking widespread agreement.'),
	(62, 'marcos_robredo_2028', 0.25, 0.15, 'News outlets reported speculation of Marcos potentially endorsing or teaming with Robredo for 2028 due to tensions with Sara Duterte and his Naga visit, but official statements from the Palace deemed it ''untimely'' and Marcos clarified it as non-political work; no broad public support or agreement observed, aligning with strong opposition or dismissal.', 'A handful of articles from major Philippine news sources (GMA, ABS-CBN, Philstar, Inquirer) covered the rumors 1-3 days ago, but searches yielded no recent X posts using relevant keywords or semantic queries since Feb 20, indicating very low current social media volume.', 0.7, '2026-02-09', 'Attention dropped significantly from 0.65 due to the subsidence of rumors following Marcos'' Naga visit without confirmation or escalation, resulting in no recent X discussions; consensus remained stable at 0.25 amid consistent skepticism.'),
	(63, 'sarah_duterte_wins_2028', 0.8, 0.6, 'Sara is frequently cited as the strongest opposition candidate (e.g., by Drilon) with dedicated supporters praising her, but countered by strong opposition pushes for Leni Robredo/Risa Hontiveros, local surveys favoring alternatives, and impeachment efforts, yielding broad but polarized support.', 'Mainstream news heavily covers Sara''s recent 2028 presidential bid announcement and reactions (e.g., Marcos'' neutrality, rivals'' comments), but limited recent X posts retrieved suggest moderate rather than viral social discussion.', 0.7, '2026-02-09', 'Consensus remained stable reflecting ongoing perception of Sara as a frontrunner amid mixed reactions; attention decreased from yesterday''s peak as social media volume appears lower with no new viral developments today.'),
	(64, 'marcos_robredo_2028', 0.25, 0.45, 'Official statements from Marcos, Robredo, and the Palace explicitly deny any political discussions or endorsements related to 2028, dismissing rumors as untimely and emphasizing service over politics; no widespread public agreement or enthusiasm for a team-up observed, with speculation limited to media optics.', 'Several major Philippine news outlets (Inquirer, GMA, Philstar, SunStar) published articles today on the Marcos-Robredo meeting and 2028 rumors, indicating it''s a recognized talking point but not dominating social media or trending virally.', 0.7, '2026-02-10', 'Attention increased moderately due to President Marcos'' recent visit to Naga City where he met Mayor Leni Robredo, sparking media speculation about a 2028 alliance, while consensus remained stable amid firm denials from both parties.'),
	(65, 'sarah_duterte_wins_2028', 0.8, 0.9, 'Political analysts and opposition leaders like Franklin Drilon acknowledge Sara Duterte as the strongest candidate with rising satisfaction ratings (+28 per SWS), though local surveys show Leni Robredo leading in some areas and scandals persist; broad acceptance of her as top contender to beat.', 'High virality from major news outlets (BBC, Al Jazeera, Inquirer, ABS-CBN) covering her candidacy declaration, running mate recruitment, and feud with Marcos, with significant X engagement on related discussions.', 0.9, '2026-02-10', 'Attention surged due to Sara Duterte''s announcement of her 2028 presidential bid around February 18, generating widespread media coverage; consensus remained stable as she is consistently viewed as the frontrunner despite opposition efforts to unite.'),
	(66, 'marcos_robredo_2028', 0.22, 0.55, 'Rumors of a potential team-up emerged from Marcos'' Naga visit and analyst speculation that BBM-endorsed Leni could beat Sara in 2028, but Palace dismissed it as ''untimely'' with no politics involved, indicating strong opposition and disbelief given 2022 rivalry.', 'Several mainstream news outlets (ABS-CBN, Inquirer, GMA, SunStar) covered the speculation post-meeting, marking it as a recognized talking point, though X posts were sparse and not highly engaged.', 0.7, '2026-02-11', 'Attention increased moderately due to recent Marcos-Robredo meeting in Naga sparking rumors in news, while consensus dipped slightly as official denials reinforced skepticism.'),
	(67, 'sarah_duterte_wins_2028', 0.75, 0.1, 'Sara Duterte''s net satisfaction rating rose to +28 per recent SWS survey, the highest among top officials, reinforcing her as a frontrunner for 2028, though tempered by opposition impeachment complaints and endorsements of Leni Robredo as ''most winnable.''', 'Searches yielded no X posts since February 11 and limited web news up to mid-February, indicating minimal current discussion.', 0.6, '2026-02-11', 'Scores show a sharp drop in attention from yesterday''s 0.9 due to fading hype after Sara''s early February presidential bid announcement, with no new discourse today; consensus slightly decreased from 0.8 amid impeachment pushes but supported by strong satisfaction ratings.'),
	(68, 'marcos_robredo_2028', 0.22, 0.55, 'Official statements from Palace and Marcos dismiss any political alliance or endorsement as ''untimely'' or non-existent; while one analyst speculated positively, social media features Leni supporters promoting her independent 2028 run without BBM, indicating strong skepticism or rejection of the proposition.', 'Moderate coverage by major outlets (ABS-CBN, Inquirer, GMA, Philstar, SunStar) on rumors following the Naga meeting, but minimal direct discussion or virality on X about team-up.', 0.7, '2026-02-12', 'Scores stable compared to yesterday; recent Marcos-Robredo meeting sparked brief media speculation on possible alliance but was swiftly dismissed by officials, preventing significant shifts.'),
	(69, 'sarah_duterte_wins_2028', 0.75, 0.75, 'Early opinion polls consistently show Sara Duterte leading the 2028 presidential race, reflecting broad support from her base, though countered by opposition narratives pushing alternatives like Leni Robredo and ongoing impeachment threats.', 'High volume of recent news articles from BBC, Al Jazeera, Inquirer, and others on her bid announcement, coupled with X discussions on political tensions, indicate significant mainstream and social media buzz.', 0.9, '2026-02-12', 'Attention surged due to Vice President Sara Duterte''s recent announcement of her 2028 presidential bid, covered extensively by major news outlets; consensus held steady as early polls affirm her frontrunner status amid the Marcos-Duterte feud.'),
	(70, 'marcos_robredo_2028', 0.24, 0.7, 'Official statements from Malacañang and Marcos dismiss rumors of political courtship or endorsement as untimely or service-focused; social media features Leni supporters pushing her 2028 candidacy independently or with others like Bam/Tulfo, with only fringe speculation of a Marcos-backed Leni.', 'Several mainstream Philippine news sources (GMA, ABS-CBN, Inquirer, SunStar) reported on the Naga visit and 2028 rumors today, indicating moderate to high virality beyond niche partisan chatter.', 0.7, '2026-02-13', 'Attention increased due to Marcos'' recent visit to Naga sparking 2028 endorsement rumors covered by multiple news outlets, while consensus stayed low amid official dismissals and lack of supportive social buzz.'),
	(71, 'sarah_duterte_wins_2028', 0.75, 0.7, 'Sara Duterte leads early 2028 polls (e.g., Tangere 43%, WR Numero ~30%) as frontrunner, suggesting broad acceptance of her strong chances despite vocal opposition criticizing her as a ''Manchurian candidate'' and promoting alternatives like Leni Robredo.', 'Ongoing mainstream news coverage (BBC, Al Jazeera, Inquirer within 24 hours) on her presidential bid and running mate recruitment, coupled with Wikipedia updates, but limited high-engagement X posts indicate high but slightly cooling virality.', 0.7, '2026-02-13', 'Scores remained largely stable compared to yesterday, with continued post-announcement coverage but no explosive new developments or viral spikes today.'),
	(73, 'sarah_duterte_wins_2028', 0.75, 0.65, 'Recent polls such as Tangere (43% lead) and others show Sara Duterte as the frontrunner for 2028 despite impeachment complaints and feud with Marcos, indicating broad acceptance of her potential victory among the public.', 'Coverage in major outlets like BBC, Al Jazeera, Inquirer, and Manila Times on her announcement and polls, but limited recent X activity suggests moderate ongoing discussion rather than peak virality.', 0.8, '2026-02-14', 'Scores slightly decreased in attention due to the presidential bid announcement being 4 days old with no major new events today, while consensus held steady supported by recent polls.'),
	(74, 'marcos_robredo_2028', 0.23, 0.65, 'Rumors of a Marcos-Robredo team-up for 2028 are dismissed by the Palace as ''untimely'' and by Marcos himself as non-political service, with no affirmative signals or public support observed; Leni Robredo''s supporters push her independent presidential bid.', 'Mainstream Philippine news outlets like Inquirer, GMA, ABS-CBN, and SunStar published multiple articles in the last 2 days on the speculation following Marcos'' Naga visit, indicating rising moderate discussion.', 0.75, '2026-02-15', 'Attention increased moderately due to recent news coverage of President Marcos'' visit to Naga sparking alliance rumors, while consensus stayed low amid official denials.'),
	(75, 'sarah_duterte_wins_2028', 0.78, 0.82, 'Recent Tangere poll (Feb 19-20) shows Sara at 43% leading preferences, with opposition leader Drilon calling her the strongest bet needing unified opposition; vocal anti-Duterte sentiment exists amid impeachment threats, but broad acceptance as frontrunner prevails.', 'High volume of mainstream and international coverage (BBC, Al Jazeera, Inquirer) on her bid announcement four days ago, today''s running mate comments, and fresh polls keep it a top political talking point.', 0.9, '2026-02-15', 'Both scores slightly increased compared to yesterday due to sustained media buzz from Sara Duterte''s recent presidential bid announcement and new poll confirmations of her lead, without any major counter-events.'),
	(76, 'marcos_robredo_2028', 0.25, 0.5, 'Strong opposition prevails as Palace and President Marcos explicitly dismissed rumors of any 2028 endorsement or team-up as ''untimely'' and purely service-oriented; only isolated pro-Robredo advocates and one analyst speculate positively, representing a tiny minority.', 'Moderate volume with several mainstream news outlets (ABS-CBN, Inquirer, GMA, Philstar) reporting on the recent Marcos-Robredo Naga meeting and sparking 2028 rumors today, but no detectable recent X posts despite searches.', 0.7, '2026-02-16', 'Attention decreased slightly from yesterday''s higher level due to official denials quelling social media buzz, while consensus held steady amid persistent skepticism.'),
	(77, 'sarah_duterte_wins_2028', 0.81, 0.87, 'Dominant narratives from recent polls (e.g., Tangere 43%, others 35%+ lead) and opposition admissions (e.g., Drilon calling her strongest contender needing unified opposition) indicate broad acceptance of her likely victory, with vocal but minority anti-Duterte posts favoring alternatives like Leni Robredo.', 'High virality from widespread news coverage (Reuters, Wikipedia updates, local outlets) on her announcement and polling leads, coupled with active X discussions on her strength despite impeachment threats.', 0.85, '2026-02-16', 'Both scores slightly increased due to Sara Duterte''s recent official announcement of her 2028 presidential bid on February 18, reinforcing her frontrunner status in polls amid impeachment discussions.'),
	(78, 'marcos_robredo_2028', 0.28, 0.3, 'Media coverage speculates on potential Marcos-Robredo alliance for 2028 following their February 21 meeting on flood control, with some analysts claiming it could help Leni beat Sara Duterte, but Palace officials call endorsements ''untimely'' and deny political motives, reflecting predominant skepticism and minimal affirmative support.', 'Discussion limited to recent news articles (e.g., Rappler, Philstar, ABS-CBN) on the Naga meeting sparking 2028 rumors, plus scattered Facebook/Reddit hypotheticals, but no X posts retrieved indicating low social media volume.', 0.6, '2026-02-17', 'Attention decreased from moderate to low due to lack of X/Twitter virality despite news speculation from Marcos'' recent Naga City visit with Robredo; consensus slightly increased but remains in strong opposition range as no real alliance signals emerged.'),
	(79, 'sarah_duterte_wins_2028', 0.82, 0.8, 'Sara Duterte is widely viewed as the leading candidate in early 2028 polls and acknowledged as the ''strongest'' or ''dominant'' contender even by opposition figures like Sen. Risa Hontiveros; while critics highlight impeachment risks and early bid as a ''gamble,'' there is broad acceptance of her strong position amid Duterte-Marcos feud.', 'Topic remains prominent with fresh articles today on her running mate recruitment and Marcos'' neutral response, plus international coverage, but X activity appears moderate post-announcement peak.', 0.85, '2026-02-17', 'Scores showed minimal movement compared to yesterday, with consensus stable due to consistent recognition of her frontrunner status and attention slightly decreasing as the announcement hype from four days ago sustains but does not intensify.'),
	(80, 'marcos_robredo_2028', 0.25, 0.25, 'Public discourse shows strong opposition to a Marcos-Robredo team-up, with the Palace deeming any endorsement ''untimely,'' Marcos denying political intent behind his Naga visit, and Leni supporters rallying for her solo 2028 presidential bid; only a single analyst speculates it could help her beat Sara.', 'Low volume of chatter confined to niche X accounts amplifying Leni2028 hashtags and a few recent news articles on fleeting endorsement speculation, overshadowed by broader 2028 election talks post-Sara Duterte''s announcement.', 0.7, '2026-02-18', 'Scores slightly decreased from yesterday as endorsement rumors sparked by Marcos'' Naga visit and Sara''s announcement were swiftly dismissed by the Palace, failing to sustain momentum.'),
	(81, 'sarah_duterte_wins_2028', 0.82, 0.95, 'Recent Tangere poll (Feb 19-20) places Sara Duterte at 43% voter preference, leading by 16 points over rivals, with supporters on X predicting a landslide win; opposition narratives frame the bid as a desperate impeachment distraction, but broad acceptance persists among her strong base.', 'Her Feb 18 presidential bid announcement, amid Marcos feud and impeachment threats, generated massive coverage across Inquirer, Rappler, ABS-CBN, international outlets like BBC/AP, and active X discourse with high-engagement posts.', 0.9, '2026-02-18', 'Consensus remained stable at a high level due to confirmatory early polls showing Sara Duterte leading by 16 points, while attention increased slightly from sustained media frenzy over her recent bid announcement, running mate tease, and political reactions.');


--
-- Name: sentiments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"public"."sentiments_id_seq"', 81, true);


--
-- PostgreSQL database dump complete
--

-- \unrestrict DbcH9Am7DhcOiy5HJbWNjHAVWL2qi6bVRW1ljROv07WWa59BaOe1jx68LlUmle3

RESET ALL;
